=== sdwfrost/model-runner-zoo/sir-ode-r/schema/output.json
{
  "$ref": "#/definitions/ModelOutput",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "ModelInput": {
      "additionalProperties": false,
      "description": "A generalized description of the input to an epidemiological model.",
      "properties": {
        "dt": {
          "type": "number"
        },
        "p": {
          "items": {
            "type": "number"
          },
          "type": "array"
        },
        "tspan": {
          "items": {
            "type": "number"
          },
          "type": "array"
        },
        "u0": {
          "items": {
            "type": "number"
          },
          "type": "array"
        }
      },
      "required": [
        "p",
        "u0",
        "tspan"
      ],
      "type": "object"
    },
    "ModelOutput": {
      "additionalProperties": false,
      "properties": {
        "metadata": {
          "$ref": "#/definitions/ModelInput"
        },
        "outputs": {
          "items": {
            "type": "number"
          },
          "type": "array"
        },
        "t": {
          "items": {
            "type": "number"
          },
          "type": "array"
        },
        "u": {
          "items": {
            "items": {
              "type": "number"
            },
            "type": "array"
          },
          "type": "array"
        }
      },
      "required": [
        "metadata",
        "t",
        "u"
      ],
      "type": "object"
    }
  }
}

=== sdwfrost/model-runner-zoo/sir-ode-julia/output/data.json
{"outputs":[0.8002017995957723,0.15845068910561175,17.515031789743066],"t":[0.0,0.05125376295105074,0.10376307747586971,0.17824813597548378,0.2677304059685344,0.37725204553811476,0.5058965407077423,0.6548646845555725,0.8240064789058144,1.0133618650812983,1.2225667242833818,1.4511802399969151,1.698604218367265,1.9641938406183541,2.247264153664538,2.5471599256834976,2.863282242676594,3.195123907006949,3.542314397356141,3.9046527556078963,4.282149162114455,4.675070739451,5.083996934901863,5.509884615950004,5.954135826785934,6.418629758021838,6.905579817448384,7.416794722769351,7.951526554549307,8.50352165708405,9.06309134107282,9.623592207793246,10.184093074513672,10.744593941234099,11.305094807954525,11.865595674674951,12.426096541395378,12.987304531560685,13.553444304173391,14.128193089376458,14.71653207974353,15.324427786173858,15.959447409419534,16.630353696411447,17.343165335810248,18.088147332112918,18.842604498499178,19.598370204405526,20.354135910311875,21.110615656811465,21.86988838350301,22.63467609292589,23.40830899740267,24.19466120498134,24.998223385111856,25.82424870283922,26.679020236513278,27.570097134575732,28.506673597132224,29.49925358714479,30.556483935352645,31.674691706290794,32.82956316232064,33.99577719420294,35.161991226085235,36.32820525796753,37.49441928984983,38.66063332173213,39.826847353614426,40.99306138549672,42.15927541737902,43.32548944926132,44.49170348114362,45.657917513025915,46.82413154490821,47.99034557679051,49.15655960867281,50.322773640555106,51.4889876724374,52.6552017043197,53.821415736202,54.9876297680843,56.153843799966594,57.32016530695381,58.4934386055348,59.67832404468312,60.880172382093676,62.10430831149228,63.356412491426305,64.64258987776603,65.96956651822836,67.34477746532261,68.77664300839216,70.27481026853644,71.85049114289455,73.5168918570938,75.2897858232621,77.18828672794324,79.23591464082206,81.46215162498274,83.90472279970955,86.61277231158697,89.65223102117889,93.11408134296093,97.12831029750858,101.88889213265672,107.70118151271193,115.0797906735761,124.97603528318618],"u":[[0.99,0.9897447274633862,0.9894799273742344,0.9890985449302906,0.9886312924833556,0.9880456340273118,0.9873378910961241,0.986490800895265,0.9854919772165159,0.9843253252731735,0.9829743588164804,0.9814201911705127,0.9796419559968427,0.9776159647252934,0.9753154901985273,0.9727099864863563,0.9697644891134315,0.9664387891338593,0.9626862869149705,0.9584526687608137,0.9536741305649392,0.9482750672648359,0.9421650017742114,0.9352345322989308,0.9273501689839064,0.9183486343520657,0.9080340517974332,0.8961909183686122,0.8826451147623376,0.8673827184281112,0.8505635385721274,0.83235914968448,0.812827362924768,0.7920303194463433,0.7700628369925376,0.7470522107554932,0.7231560939279358,0.6985270232129892,0.6731773506380785,0.6471539752416983,0.6204634620182894,0.5930967103581645,0.5650186260361161,0.5362112700187648,0.5068617731251374,0.47783579595887526,0.45035619741053473,0.4248793465381585,0.40149561992935395,0.38016337460552807,0.36076702591870313,0.3431627784344256,0.32719550272873665,0.31271145690354685,0.29956449695856896,0.28761927621484557,0.27675214384170344,0.2668526651466519,0.25782410671483746,0.24958981961419396,0.24211346081886032,0.23543758713423643,0.22965914854750583,0.22478483488702897,0.22071457973747208,0.21731378933466525,0.21447076618693317,0.21209278977482984,0.21010284270400173,0.20843689649111946,0.2070416705510421,0.20587278534867132,0.20489324101393125,0.2040721634149868,0.20338376955185883,0.20280651271981637,0.2023223751237394,0.2019162815984664,0.20157561296955046,0.2012898015499513,0.2010499944749188,0.20084877317199887,0.20067991936456292,0.2005382077608851,0.2004186340860212,0.2003174816648743,0.2002317187553116,0.20015891295388932,0.20009707712253372,0.20004457749343876,0.20000005819191588,0.19996238806447392,0.19993061419272218,0.19990392847950245,0.1998816404892707,0.19986315597430676,0.19984795957839852,0.19983560088683616,0.19982568312375895,0.1998178538338275,0.19981179750381511,0.19980723018820928,0.19980389451084762,0.19980155673579914,0.19980000478083057,0.1997990473964525,0.19979851480267719,0.19979826082014876,0.19979816649967597],[0.01,0.010126330388429392,0.010257340667480469,0.010445967325429835,0.010676962804115507,0.01096633689285671,0.011315798532872894,0.011733727756940765,0.01222604409272466,0.012800431938627347,0.013464687236434097,0.014227685953984284,0.015099149457884478,0.016090023244305685,0.01721253761420005,0.01848053055852161,0.019909663436232027,0.02151772205425973,0.02332503863160179,0.02535495138495166,0.0276344151197108,0.030194771296704184,0.03307273984044753,0.03631166702282771,0.03996298280868268,0.044087445318872626,0.04875441914777658,0.05403334281432719,0.05996400806515639,0.06650493474208458,0.07353349092793032,0.08092029228492315,0.08857939148271214,0.09641684094539386,0.10432047620394112,0.11216250486880126,0.11980355082922217,0.1271069250699585,0.13397399413494607,0.14028501049384143,0.14591669052057146,0.1507287637588108,0.15455742317404572,0.15719954259213026,0.15840410997003654,0.15794456069975618,0.15581006594699984,0.15217018300254043,0.1472496303503879,0.1412841037463865,0.13449606106141831,0.12708649409311268,0.11923014743630242,0.11107559324910568,0.1027468332275529,0.09434584957969772,0.08595514506310649,0.07764162298118424,0.06946043133560116,0.06146512513108327,0.053735055965830794,0.04643039314858998,0.03978382814696334,0.03393169646836806,0.028865204549573004,0.024501906146831627,0.020760426758702617,0.01756358018014945,0.0148401381774056,0.012525668567140043,0.010562752264957271,0.008900804806242163,0.007495661807739018,0.006309038224073299,0.005307934922700787,0.004464040074958999,0.0037531545943708,0.0031546582968081244,0.0026510250235500105,0.0022273894618932144,0.0018711649363585172,0.001571709386326064,0.0013200356351253312,0.0011085437206000085,0.0009298964948375607,0.0007786323185818363,0.0006502818850571867,0.0005412507260924723,0.0004485958228192877,0.00036989282256705774,0.00030312627292337495,0.0002466122271280811,0.00019893015589729672,0.00015887397116608117,0.00012541209358588005,9.765581437784862e-5,7.483375944170633e-5,5.6271257459469214e-5,4.137359712967824e-5,2.9612202117867822e-5,2.0513674356270147e-5,1.3651814514262173e-5,8.640182665297857e-6,5.1277491835085444e-6,2.7959478756087676e-6,1.3574696272422222e-6,5.572379506875229e-7,1.756234141779242e-7,3.3904552052180275e-8],[0.0,0.0001289421481844566,0.0002627319582850147,0.00045548774427950773,0.0006917447125289638,0.0009880290798315137,0.0013463103710030196,0.0017754713477943183,0.0022819786907592953,0.002874242788199014,0.003560953947085292,0.004352122875502951,0.0052588945452727775,0.006294012030400752,0.007471972187272642,0.008809482955122044,0.01032584745033635,0.012043488811880934,0.01398867445342757,0.016192379854234468,0.0186914543153498,0.02153016143845983,0.02476225838534104,0.028453800678241343,0.032686848207410725,0.03756392032906148,0.04321152905479004,0.049775738817060565,0.05739087717250597,0.06611234682980427,0.07590297049994225,0.08672055803059671,0.09859324559251977,0.11155283960826275,0.12561668680352117,0.1407852843757055,0.157040355242842,0.17436605171705233,0.1928486552269755,0.2125610142644604,0.23361984746113923,0.2561745258830248,0.28042395078983834,0.30658918738910523,0.33473411690482635,0.3642196433413689,0.39383373664246585,0.4229504704593014,0.45125474972025853,0.47855252164808576,0.5047369130198789,0.529750727472462,0.5535743498349612,0.5762129498473478,0.5976886698138785,0.6180348742054571,0.6372927110951906,0.6555057118721643,0.6727154619495619,0.6889450552547234,0.7041514832153095,0.7181320197171742,0.7305570233055314,0.7412834686446035,0.7504202157129554,0.7581843045185036,0.7647688070543646,0.770343630045021,0.775057019118593,0.7790374349417408,0.782395577184001,0.7852264098450868,0.7876110971783301,0.7896187983609403,0.7913082955254407,0.792729447205225,0.7939244702818902,0.794929060104726,0.7957733620069,0.796482808988156,0.7970788405887231,0.7975795174416754,0.7980000450003121,0.7983532485185152,0.7986514694191414,0.798903886016544,0.7991179993596315,0.7992998363200184,0.7994543270546473,0.7995855296839944,0.7996968155351609,0.7997909997083982,0.7998704556513808,0.7999371975493317,0.7999929474171437,0.8000391882113156,0.80007720666216,0.8001081278557046,0.8001329432791116,0.8001525339640547,0.8001676888218288,0.8001791179972766,0.8001874653064873,0.8001933155150177,0.8001971992712942,0.8001995951339206,0.8002009279593724,0.8002015635564373,0.8002017995957723]],"metadata":{"tspan":[0.0,10000.0],"u0":[0.99,0.01,0.0],"dt":1.0,"p":[0.5,0.25]}}

=== sdwfrost/model-runner-zoo/sir-ode-python/output/data.json
{
  "metadata": {
    "p": [
      0.5,
      0.25
    ],
    "u0": [
      0.99,
      0.01,
      0.0
    ],
    "tspan": [
      0.0,
      10000.0
    ]
  },
  "t": [
    0.0,
    0.09284972135797114,
    1.0213469349376825,
    4.730308099257948,
    10.228677689262607,
    18.31425261516454,
    27.82753051477629,
    37.199522058936026,
    43.77195890488725,
    50.34439575083847,
    57.34851443181673,
    64.42717783073053,
    71.96730511165129,
    80.42082880784326,
    90.40351386704342,
    102.75262015173696
  ],
  "u": [
    [
      0.99,
      0.9895352372107644,
      0.9842749739892699,
      0.9474778577502123,
      0.8111285685696914,
      0.4692702181050562,
      0.2718634256070777,
      0.2237105381717018,
      0.2138438719048309,
      0.21009771771207014,
      0.20861408640743825,
      0.2080777324610784,
      0.2078800876636019,
      0.20781024841788517,
      0.20778823424156034,
      0.20778263799851357
    ],
    [
      0.01,
      0.01022997899299957,
      0.012825206057771092,
      0.030572187075150636,
      0.08927463371470634,
      0.15736741584273783,
      0.07055669501889276,
      0.021022315049174553,
      0.008321134019081999,
      0.003227693264226679,
      0.0011672397559916443,
      0.0004163124271337634,
      0.0001387792007069591,
      4.0604932500547665e-05,
      9.647686788777695e-06,
      1.7771210413156543e-06
    ],
    [
      0.0,
      0.00023478379623604638,
      0.0028998199529591097,
      0.021949955174637145,
      0.09959679771560237,
      0.37336236605220613,
      0.6575798793740296,
      0.7552671467791238,
      0.7778349940760872,
      0.7866745890237034,
      0.7902186738365703,
      0.791505955111788,
      0.7919811331356913,
      0.7921491466496144,
      0.7922021180716511,
      0.7922155848804453
    ]
  ],
  "outputs": [
    0.7922155848804453,
    0.15742164632511513,
    18.119443842031806
  ]
}
